# Use the official Node.js image as a base
FROM node:14

# Set the working directory
WORKDIR /src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli@16

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that Angular will run on
EXPOSE 4200

# Start the application using `ng serve`
CMD ["ng", "serve", "--host", "0.0.0.0"]
